version: '3'
services: 
  db:
    build: src/db
    environment:
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
  server:
    build: src/server
    depends_on:
      - db
    environment:
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
      - ZMS_HOST
    ports:
      - "8484:8484"
      - "7575-7578:7575-7578"
